### ISSUE TITLE
Flexible ratio container for videos or cards

### ISSUE THREAD

**Issue by nitipit** [nitipit/bits-ui#12]
It would be nice to have flexible aspect ratio container for videos or card like components.
Such as
- 4:3
- 16:9
- 21:9

Sample codes from https://css-tricks.com/aspect-ratio-boxes/

HTML
```html
<div style="--aspect-ratio:815/419;">
</div>

<div style="--aspect-ratio:16/9;">
</div>

<!-- even single value -->
<div style="--aspect-ratio:1.4;">
</div>
```

CSS
```css
[style*="--aspect-ratio"] > :first-child {
  width: 100%;
}
[style*="--aspect-ratio"] > img {  
  height: auto;
} 
@supports (--custom:property) {
  [style*="--aspect-ratio"] {
    position: relative;
  }
  [style*="--aspect-ratio"]::before {
    content: "";
    display: block;
    padding-bottom: calc(100% / (var(--aspect-ratio)));
  }  
  [style*="--aspect-ratio"] > :first-child {
    position: absolute;
    top: 0;
    left: 0;
    height: 100%;
  }  
}
```
